apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: ubuntu/apache2:latest
        ports:
        - containerPort: 80
          name: n1
        - containerPort: 443
          name: n2
